[package]
name = "example"
version = "0.1.0"
authors = ["JLer <472102489@qq.com>"]
edition = "2018"

[dependencies]
util = { path = "../util" }
client = { path = "../client" }
protocol = { path = "../protocol" }

bevy = "0.5"
rand = "0.8"
