[package]
name = "util"
version = "0.1.0"
authors = ["JLer <472102489@qq.com>"]
edition = "2018"

[dependencies]
serde = {version = "1", features = ["derive"]}
serde_json = "1"
base64 = "0.13"
clipboard = "0.5.0"
libaes = "0.6"
rand = "0.7"
rsa = "0.3"
sha2 = "0.9"
bytes = "1.0"
bevy = "0.4"
