[package]
name = "common"
version = "0.1.0"
authors = ["JLer <472102489@qq.com>"]
edition = "2018"

[dependencies]
protocol = { path = "../protocol" }
data = { path = "../data" }

glam = "0.13.1"
rand = "0.8"
